# Generated by Django 6.0.4 on 2026-04-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='зарезервировано', max_length=50, verbose_name='Статус')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата транзакции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='активен', max_length=50, verbose_name='Статус')),
                ('conclusion_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заключения')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер платы')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('employer_rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка от заказчика')),
                ('freelancer_rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка от фрилансера')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.freelancer')),
            ],
        ),
    ]
