# Generated by Django 6.0.4 on 2026-04-16 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('required_skills', models.TextField(verbose_name='Необходимые навыки')),
                ('expected_payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Предполагаемая плата')),
                ('deadline', models.DateTimeField(verbose_name='Срок выполнения')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.employer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderResponse',
            fields=[
                ('response_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название/Текст отклика')),
                ('status', models.CharField(default='рассматривается', max_length=50, verbose_name='Статус')),
                ('response_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='users.freelancer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='orders.order')),
            ],
        ),
    ]
